name = "apps-cf"
main = "build/index.js"
compatibility_date = "2024-12-01"

[assets]
directory = "./frontend/dist"
binding = "ASSETS"

[build]
command = "worker-build --release"

[[kv_namespaces]]
binding = "APPS_DATA"
id = "f1278ff28c664a6eae27e8d866a1fc62"

[vars]
APP_URL = "https://apps.sential.eu.cc"
GITHUB_CLIENT_ID = "Ov23liNm6UI3Scq74VxG"

routes = [
  { pattern = "apps.sential.eu.cc", custom_domain = true }
]
